spring:
    application:
      name : bootTest
      main :
        banner-mode: off
        profiles.active: test

server:
      port: 8088
---
spring:
  profile: test
  datasource:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/g2monitor?useUnicode=true&characterEncoding=utf-8
      username: root
      password: root


